import type { LandingConfig } from "@/lib/supabase/types";

export const INDUSTRY_KEYS = ["debt", "rental", "broadband", "invest", "realestate", "medical"] as const;
export type IndustryKey = typeof INDUSTRY_KEYS[number];

export const INDUSTRY_LABELS: Record<IndustryKey, string> = {
    debt: "개인회생·파산",
    rental: "정수기·렌탈",
    broadband: "인터넷·통신",
    invest: "주식·투자",
    realestate: "부동산·임대",
    medical: "의료·병원",
};

export const INDUSTRY_ICONS: Record<IndustryKey, string> = {
    debt: "⚖️",
    rental: "💧",
    broadband: "📶",
    invest: "📈",
    realestate: "🏠",
    medical: "🏥",
};

export function getIndustryDefault(industry: string): LandingConfig {
    const defaults: Record<string, LandingConfig> = {
        debt: {
            brandName: "채무 상담 센터",
            brandColor: "#3182f6",
            brandIcon: "⚖️",
            step1Question: "현재 총 채무 금액은?",
            step1Options: ["1천만원 미만", "1~3천만원", "3~5천만원", "5천만~1억", "1억~3억", "3억 이상"],
            step1Note: "정확한 금액을 알수록 더 정확한 상담이 가능합니다",
            step2Question: "현재 직업 상태는?",
            step2Options: ["직장인", "자영업자", "무직/실직", "프리랜서", "주부", "기타"],
            step3Question: "현재 상황을 자세히 알려주세요",
            step3Placeholder: "예: 월 소득 200만원, 카드빚 3천만원, 연체 6개월...",
            page2Copy: "채무 탕감 가능액을 확인하기 위해",
            consentRequired: "개인정보 수집·이용 동의 (채무 상담 안내 목적)",
            consentOptional: "마케팅 정보 수신 + 상담 사례 익명 활용 동의",
            companyName: "",
            companyRep: "",
            companyBizNum: "",
            companyAddress: "",
            legalNote: "광고책임 변호사 별도 표기 · 변호사법 §34의2 의무 표시\n본 광고는 법률 상담 안내이며, 결과는 사안에 따라 다를 수 있습니다.",
            ctaText: "내 채무 탕감 가능액 무료 진단 시작",
        },
        rental: {
            brandName: "정수기 비교 센터",
            brandColor: "#3182f6",
            brandIcon: "💧",
            step1Question: "어떤 제품을 찾고 계신가요?",
            step1Options: ["냉온정수기", "직수형 정수기", "얼음정수기", "공기청정기", "비데", "기타"],
            step1Note: "복수 선택 시 원하시는 제품을 알려주세요",
            step2Question: "현재 주거 형태는?",
            step2Options: ["아파트", "빌라/연립", "오피스텔", "단독주택", "상가/사무실", "기타"],
            step3Question: "추가로 알려주실 사항이 있으신가요?",
            step3Placeholder: "예: 가족 수 4명, 2년 약정 선호, 코웨이 비교 희망...",
            page2Copy: "맞춤 견적을 안내해 드리기 위해",
            consentRequired: "개인정보 수집·이용 동의 (정수기 비교 안내 목적)",
            consentOptional: "마케팅 정보 수신 동의",
            companyName: "",
            companyRep: "",
            companyBizNum: "",
            companyAddress: "",
            legalNote: "본 광고는 렌탈 상품 안내이며, 실제 가격은 상담 후 확정됩니다.",
            ctaText: "내 맞춤 정수기 무료 견적 시작",
        },
        broadband: {
            brandName: "통신비 절감 센터",
            brandColor: "#3182f6",
            brandIcon: "📶",
            step1Question: "원하시는 상품은?",
            step1Options: ["인터넷만", "인터넷+TV", "인터넷+TV+전화", "휴대폰만", "결합상품", "기타"],
            step1Note: "현재 사용 중인 통신사와 비교해 드립니다",
            step2Question: "현재 사용 중인 통신사는?",
            step2Options: ["KT", "SKT", "LG U+", "SK브로드밴드", "없음/신규", "기타"],
            step3Question: "추가로 알려주실 사항이 있으신가요?",
            step3Placeholder: "예: 월 5만원, 계약 만료 3개월 후, 인터넷+TV 결합 원함...",
            page2Copy: "절감 가능한 통신비를 안내해 드리기 위해",
            consentRequired: "개인정보 수집·이용 동의 (통신 상담 안내 목적)",
            consentOptional: "마케팅 정보 수신 동의",
            companyName: "",
            companyRep: "",
            companyBizNum: "",
            companyAddress: "",
            legalNote: "본 광고는 통신 서비스 안내이며, 실제 요금은 상담 후 확정됩니다.",
            ctaText: "내 통신비 무료 절감 진단 시작",
        },
        invest: {
            brandName: "투자 교육 센터",
            brandColor: "#3182f6",
            brandIcon: "📈",
            step1Question: "관심 있는 투자 분야는?",
            step1Options: ["국내 주식", "해외 주식", "ETF/펀드", "부동산 투자", "가상자산", "기타"],
            step1Note: "현재 투자 경험에 맞는 강좌를 안내해 드립니다",
            step2Question: "투자 경험은?",
            step2Options: ["완전 초보", "6개월 미만", "1년 미만", "2년 미만", "3년 이상", "5년 이상"],
            step3Question: "추가로 알려주실 사항이 있으신가요?",
            step3Placeholder: "예: 월 50만원 투자 중, 단기 수익 목표, 기술적 분석 배우고 싶음...",
            page2Copy: "맞춤 강좌를 안내해 드리기 위해",
            consentRequired: "개인정보 수집·이용 동의 (투자 교육 안내 목적)",
            consentOptional: "마케팅 정보 수신 동의",
            companyName: "",
            companyRep: "",
            companyBizNum: "",
            companyAddress: "",
            legalNote: "본 광고는 교육 서비스 안내이며, 투자에는 손실 위험이 있습니다. 금융투자협회 등록 강사 안내.",
            ctaText: "내 맞춤 투자 강좌 무료 안내 시작",
        },
        realestate: {
            brandName: "부동산 분양 센터",
            brandColor: "#3182f6",
            brandIcon: "🏠",
            step1Question: "관심 있는 부동산 유형은?",
            step1Options: ["아파트 분양", "재건축/재개발", "오피스텔", "빌라/연립", "상가/사무실", "기타"],
            step1Note: "현재 시장 상황에 맞는 정보를 안내해 드립니다",
            step2Question: "희망 지역은?",
            step2Options: ["서울", "경기/인천", "부산", "대구/경북", "광주/전남", "기타"],
            step3Question: "추가로 알려주실 사항이 있으신가요?",
            step3Placeholder: "예: 예산 5억, 2~3인 가구, 역세권 선호, 전세 만기 6개월...",
            page2Copy: "맞춤 매물 정보를 안내해 드리기 위해",
            consentRequired: "개인정보 수집·이용 동의 (부동산 상담 안내 목적)",
            consentOptional: "마케팅 정보 수신 동의",
            companyName: "",
            companyRep: "",
            companyBizNum: "",
            companyAddress: "",
            legalNote: "공인중개사 정식 등록 안전 거래. 본 광고는 부동산 안내이며, 실제 가격은 시장 상황에 따라 다를 수 있습니다.",
            ctaText: "내 맞춤 부동산 무료 상담 시작",
        },
        medical: {
            brandName: "의료 상담 센터",
            brandColor: "#3182f6",
            brandIcon: "🏥",
            step1Question: "관심 있는 진료 분야는?",
            step1Options: ["피부과", "성형외과", "치과", "한의원", "내과/가정의학", "기타"],
            step1Note: "전문의 자격 인증 병원을 안내해 드립니다",
            step2Question: "주요 증상이나 목적은?",
            step2Options: ["미용/개선", "통증 치료", "건강 검진", "만성 질환", "다이어트", "기타"],
            step3Question: "추가로 알려주실 사항이 있으신가요?",
            step3Placeholder: "예: 피부 트러블 심함, 코 성형 관심, 가까운 병원 원함...",
            page2Copy: "맞춤 병원을 안내해 드리기 위해",
            consentRequired: "개인정보 수집·이용 동의 (의료 상담 안내 목적)",
            consentOptional: "마케팅 정보 수신 동의",
            companyName: "",
            companyRep: "",
            companyBizNum: "",
            companyAddress: "",
            legalNote: "전문의 자격 인증 + 의료법 사전심의 인증병원 안내.\n본 광고는 의료 상담 안내이며, 실제 진단은 전문의와 상담 후 진행됩니다.",
            ctaText: "내 증상 무료 상담 시작",
        },
    };
    return defaults[industry] ?? defaults["debt"]!;
}
